### ISSUE TITLE
Run only a subset of tests on PRs that only modify the manual

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaCI/julia-buildkite#243]
If a PR only modifies the manual, then we only need to run a subset of jobs, including:
1. Build a regular (non-assert) build of Julia on x86_64-linux-gnu
2. Build the docs
3. Run the doctests

**Comment by staticfloat** [comment]
I think the way to do this is to have a "filter" that looks at the diff, and skips launching a job if the diff does not contain changes to a particular group of files.  We can also construct this negatively, e.g. filter out elements of a diff, and then run if any diff remains.

The way I'm imagining this is to write a buildkite plugin that does something like the following:

```
steps:
  - label: launch jobs
    plugins:
      - JuliaCI/diff-filter#v1:
          docs:
            # Only run docs if we have a diff that changes something in `doc/`
            mode: positive
            patterns:
              - "doc/**"
          build:
            # Run build if anything changes, excluding changes to docs, README, etc...
            mode: negative
            patterns:
              - "doc/**"
              - "README.md"
    commands: |
      if [[ $${BUILDKITE_PLUGIN_DIFF_FILTER_TRIGGERED_DOCS} == 1 ]]; then
          buildkite-agent upload docs.yml
      fi
      if [[ $${BUILDKITE_PLUGIN_DIFF_FILTER_TRIGGERED_BUILD} == 1 ]]; then
          buildkite-agent upload build.yml
      fi
```
